_wandb:
    value:
        cli_version: 0.22.1
        e:
            mkq8vp5538d34giy4v2kqlrsnturdorn:
                args:
                    - config/vit_classification_task_0.json
                codePath: vit_classification.py
                codePathLocal: vit_classification.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1999376478208"
                        used: "512457064448"
                email: aqj.shi@gmail.com
                executable: C:\Users\aqjsh\Desktop\ViT_On_QM9_Filtered\venv\Scripts\python.exe
                git:
                    commit: 081cb2e1acaea5639f1c4a1ba6ba5aff3424981c
                    remote: https://github.com/aqjshi/ViT_On_QM9_Filtered.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-0562d0c0-a864-1c70-2ed4-996a1f8ffe3c
                host: Laptop
                memory:
                    total: "67756339200"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\aqjsh\Desktop\ViT_On_QM9_Filtered\vit_classification.py
                python: CPython 3.12.7
                root: C:\Users\aqjsh\Desktop\ViT_On_QM9_Filtered
                startedAt: "2026-09-24T01:20:06.261986Z"
                writerId: mkq8vp5538d34giy4v2kqlrsnturdorn
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 16
            "4": 3.12.7
            "5": 0.22.1
            "8":
                - 3
            "12": 0.22.1
            "13": windows-amd64
TASK:
    value: 0
augment:
    value: true
batch_size:
    value: 256
clamp_range:
    value: 20
emb_dim:
    value: 256
emb_dropout:
    value: 0.23
embedding_dim:
    value: 256
embedding_dropout_rate:
    value: 0.23
epochs:
    value: 10
grad_clip:
    value: 0.4677
learning_rate:
    value: 0.00029
lr:
    value: 0.00029
mlp_dropout:
    value: 0.28261284
mlp_dropout_rate:
    value: 0.28261284
mlp_size:
    value: 256
num_aug_samples:
    value: 50000
num_heads:
    value: 2
num_transformer_layers:
    value: 6
only_mask:
    value: true
scaler:
    value: null
scheduler:
    value: true
test_ids:
    value: '[101480  89049  54595 ...  89613  39951  79251]'
use_clamping:
    value: false
use_reflection:
    value: false
weight_decay:
    value: 2.751984133978333e-05
